#!/usr/bin/env python3
import json
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RUNTIME_ENV = PROJECT_ROOT / ".env.runtime"
OPENCLAW_JSON = Path.home() / ".openclaw" / "openclaw.json"


def _load_openclaw_config(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"未找到 OpenClaw 配置文件: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    gw = data.get("gateway", {})
    port = gw.get("port", 3333)
    token = ((gw.get("auth") or {}).get("token") or "").strip()
    bind = (gw.get("bind") or "").strip() or "loopback"
    return int(port), token, bind


def main():
    port, token, bind = _load_openclaw_config(OPENCLAW_JSON)

    # Docker 容器内默认访问宿主机网关
    base_url = f"http://host.docker.internal:{port}"

    lines = [
        "# Auto-generated by scripts/sync_openclaw_gateway.py",
        f"OPENCLAW_BASE_URL={base_url}",
        f"OPENCLAW_GATEWAY_TOKEN={token}",
        "",
    ]
    RUNTIME_ENV.write_text("\n".join(lines), encoding="utf-8")
    os.chmod(RUNTIME_ENV, 0o600)

    token_hint = "已写入" if token else "为空"
    print(f"[ok] 已同步网关配置 -> {RUNTIME_ENV}")
    print(f"     OPENCLAW_BASE_URL={base_url}")
    print(f"     OPENCLAW_GATEWAY_TOKEN={token_hint}")
    if bind != "loopback":
        print(f"[warn] gateway.bind={bind}，请确认容器可访问宿主机")


if __name__ == "__main__":
    main()
